(async()=>{
await window.contentReady;
const $=s=>document.querySelector(s), form=$('#editor'), status=$('#admin-status');let data=structuredClone(window.RAW_CONTENT),uploaded='',editing=null;
const message=s=>status.textContent=s;
try{const stored=localStorage.getItem('manar-content');if(stored)data=window.validateContent(JSON.parse(stored));}catch{message('تعذرت قراءة المسودة المحلية. يمكنك استيراد النسخة الاحتياطية.');}
SCHOOL.gallery.forEach(g=>{const option=document.createElement('option');option.value=g.src;option.textContent=g.category+' — '+g.title;$('#image').append(option);});
const preview=()=>{$('#image-preview').src=uploaded||$('#image').value;};$('#image').onchange=()=>{uploaded='';$('#upload').value='';preview();};preview();
const save=next=>{try{const valid=window.validateContent(next);localStorage.setItem('manar-content',JSON.stringify(valid));data=valid;render();return true;}catch(e){message('تعذر الحفظ: '+e.message+'؛ قد تكون مساحة المتصفح ممتلئة. صدّر نسخة احتياطية وقلّل حجم الصور.');return false;}};
function reset(){form.reset();editing=null;uploaded='';$('#editor-title').textContent='إضافة محتوى جديد';$('#date').value=new Date().toLocaleDateString('en-CA');preview();}
function render(){const list=$('#admin-list');list.replaceChildren();for(const type of ['news','events'])for(const item of data[type]){const row=document.createElement('article');row.className='admin-item';const title=document.createElement('h3');title.textContent=item.title;const info=document.createElement('p');info.textContent=(type==='news'?'خبر':'فعالية')+' · '+item.date;const edit=document.createElement('button');edit.className='btn secondary small';edit.textContent='تعديل';edit.onclick=()=>{reset();editing={type,slug:item.slug};form.elements.type.value=type;for(const key of ['slug','title','date','category','location','excerpt'])form.elements[key].value=item[key];form.elements.content.value=item.content.join('\n');if(item.image.startsWith('data:'))uploaded=item.image;else $('#image').value=item.image;preview();$('#editor-title').textContent='تعديل المحتوى';form.scrollIntoView({behavior:'smooth'});};const del=document.createElement('button');del.className='btn secondary small';del.textContent='حذف';del.onclick=()=>{if(!confirm('حذف «'+item.title+'» من المسودة؟'))return;const next=structuredClone(data);next[type]=next[type].filter(n=>n.slug!==item.slug);if(save(next)){message('حُذف العنصر من المسودة.');if(editing?.slug===item.slug)reset();}};row.append(title,info,edit,del);list.append(row);}if(!list.children.length)list.textContent='لا توجد إضافات بعد. أضف أول خبر أو فعالية من النموذج.';}
$('#upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){message('اختر صورة JPG أو PNG أو WebP بحجم لا يزيد عن 2 ميغابايت.');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{uploaded=reader.result;preview();};reader.onerror=()=>message('تعذرت قراءة الصورة.');reader.readAsDataURL(file);};
form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));const type=values.type;delete values.type;values.slug=editing?.slug||'post-'+crypto.randomUUID();values.image=uploaded||$('#image').value;values.content=values.content.split('\n').filter(t=>t.trim());const next=structuredClone(data);if(editing)next[editing.type]=next[editing.type].filter(n=>n.slug!==editing.slug);next[type].unshift(values);if(save(next)){reset();message('حُفظت المسودة محليًا. يمكنك معاينتها أو تصديرها للنشر.');}};
$('#reset-editor').onclick=reset;
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('صُدّر الملف. ارفعه بدل content.json في الموقع المستضاف لتظهر التحديثات للجميع.');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>15*1024*1024)throw Error('الملف أكبر من 15 ميغابايت');const imported=window.validateContent(JSON.parse(await file.text()));if(confirm('استبدال المسودة الحالية بمحتوى الملف المستورد؟')&&save(imported)){reset();message('تم استيراد المحتوى وحفظه محليًا.');}}catch(error){message('تعذر الاستيراد: '+error.message);}e.target.value='';};
reset();render();
})();

