window.appReady = (async () => {
'use strict';
await window.contentReady;
const S = window.SCHOOL;
S.countryCodeConfirmed = true;
S.address = 'عمران - شارع 22 مايو - ذعوان - أمام حوش الزبيدي';
S.hours = 'من السبت إلى الأربعاء';
S.mapUrl = 'https://maps.app.goo.gl/gwPcuv1QncjFPoF78';
S.facebook = 'https://www.facebook.com/manar00000000/';
const page=document.body.dataset.page||'home',base=document.body.dataset.base||'./';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>/^(data:image\/|https?:)/.test(p)?p:base+p;
const paths={home:'index.html',about:'about.html',stages:'stages.html',programs:'programs.html',activities:'activities.html',news:'news.html',gallery:'gallery.html',admissions:'admissions.html',contact:'contact.html'};
const labels={home:'الرئيسية',about:'عن المدرسة',stages:'المراحل التعليمية',programs:'البرامج',activities:'الأنشطة',news:'الأخبار',gallery:'معرض الصور والفيديوهات',admissions:'التسجيل والقبول',contact:'تواصل معنا'};
const icons={arrow:'M19 12H5m6-6-6 6 6 6',book:'M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2Z',cap:'m2 9 10-5 10 5-10 5Zm4 3v5c4 3 8 3 12 0v-5m4-3v8',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6',heart:'M20 5c-3-3-7-1-8 2-1-3-5-5-8-2-5 5 3 11 8 15 5-4 13-10 8-15Z',users:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3m20 0v-3a4 4 0 0 0-3-4M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm8 0a4 4 0 0 1 0 8',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z',grid:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',flask:'M9 3h6M10 3v7L4 19c-1 2 1 2 2 2h12c1 0 3 0 2-2l-6-9V3M7 15h10',monitor:'M3 4h18v13H3Zm5 17h8m-4-4v4',award:'M16 3H8v7a4 4 0 0 0 8 0Zm-8 2H4v3c0 3 4 3 4 3m8-6h4v3c0 3-4 3-4 3m-4 3v6m-4 0h8',calendar:'M4 5h16v16H4ZM8 3v4m8-4v4M4 11h16m-12 4h2m4 0h2',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',phone:'M7 3H3c-1 10 8 19 18 18v-4l-5-2-2 2c-3-1-6-4-7-7l2-2Z',wa:'M21 11.5A9 9 0 0 1 8 20l-5 1 1-5a9 9 0 1 1 17-4.5ZM8 7c-2 4 2 8 6 9l2-2-3-2-1 1-2-2 1-1Z',facebook:'M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z',menu:'M4 6h16M4 12h16M4 18h16',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',ball:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7l5 4-2 6H9l-2-6ZM12 3v4m9 5-4-1m-2 6 2 3m-8-3-2 3m-4-8 4-1',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8',palette:'M12 3a9 9 0 1 0 0 18c3 0 1-4 3-4h3c5 0 5-14-6-14ZM7 9h.01M11 6h.01M16 8h.01M6 14h.01',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',target:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-4 0a5 5 0 1 1-10 0 5 5 0 0 1 10 0Zm-5-1v2',mail:'M3 5h18v14H3Zm0 0 9 8 9-8',share:'M8 12 17 6M8 12l9 6M7 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM19 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm0 12a3 3 0 1 0 0 6 3 3 0 0 0 0-6'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.book}"/></svg>`;
const wa=t=>'https://wa.me/'+S.countryCode+S.phone+'?text='+encodeURIComponent(t||'السلام عليكم، أود الاستفسار عن مدارس منار العلم النموذجية.');
const external='target="_blank" rel="noopener noreferrer"';
const link=(p,t,c='text-link')=>`<a class="${c}" href="${url(p)}">${t}${icon('arrow')}</a>`;
const photo=(src,alt,c='',eager=false)=>`<img src="${url(src)}" alt="${esc(alt)}" class="${c}" width="960" height="720" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const brand=()=>`<a class="brand" href="${url('index.html')}" aria-label="مدارس منار العلم النموذجية - الرئيسية"><img src="${url('assets/logo.png')}" width="65" height="70" alt="شعار مدارس منار العلم النموذجية"><span><strong>منار العلم النموذجية</strong><small>جيل صاعد.. لغد واعد</small></span></a>`;
function chrome(){
$('#site-header').innerHTML=`<a class="skip-link" href="#main">انتقل إلى المحتوى</a><div class="topbar"><div class="container"><span class="location-top">${esc(S.address)}</span><div class="topbar-links"><a href="${S.facebook}" ${external} aria-label="صفحة مدارس منار العلم النموذجية على فيسبوك">${icon('facebook')}<span>فيسبوك</span></a><a href="${wa()}" ${external}>نرافق أبناءكم من أول خطوة ${icon('wa')} <bdi>+967 773 583 041</bdi></a></div></div></div><header class="header"><div class="container header-inner">${brand()}<nav class="nav" id="navigation" aria-label="القائمة الرئيسية">${Object.entries(labels).map(([id,l])=>`<a href="${url(paths[id])}" ${page===id||page==='article'&&id==='news'?'aria-current="page"':''}>${l}</a>`).join('')}</nav><button class="menu-toggle" aria-label="فتح القائمة" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button>${link('admissions.html','سجّل الآن','btn small header-cta')}</div></header>`;
$('#site-footer').innerHTML=`<footer class="footer"><div class="container"><div class="footer-grid"><div>${brand()}<p>معرفة تنير العقول، وقيم تبني الإنسان. نرافق أبناءنا من الصف الأول إلى التاسع في رحلة تعلّم وطموح.</p><div class="footer-social"><a class="btn-social" href="${S.facebook}" ${external} aria-label="صفحة مدارس منار العلم النموذجية على فيسبوك">${icon('facebook')}<span>صفحتنا على فيسبوك</span></a></div></div><div><h3>اكتشف المدرسة</h3><div class="footer-links">${['about','programs','activities','gallery','news'].map(id=>`<a href="${url(paths[id])}">${labels[id]}</a>`).join('')}</div></div><div><h3>نبدأ الرحلة معًا</h3><div class="footer-links">${S.stages.map(s=>`<a href="${url('stages.html#'+s.id)}">${s.grades}</a>`).join('')}<a href="${url('admissions.html')}">التسجيل والقبول</a><a href="${url('contact.html#visit')}">احجز زيارة</a></div></div><div><h3>يسعدنا تواصلكم</h3><div class="footer-links"><a href="${S.mapUrl}" ${external}>${esc(S.address)}</a><a href="tel:+967773583041"><bdi>+967 773 583 041</bdi></a><span>${S.hours}</span><a href="${wa()}" ${external}>تواصل معنا على واتساب ←</a><a href="${S.facebook}" ${external}>صفحتنا على فيسبوك ←</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} مدارس منار العلم النموذجية. جميع الحقوق محفوظة.</span><span>بالعلم نرتقي، وبالقيم نُضيء المستقبل.</span></div></div></footer><a class="floating-wa" href="${wa()}" ${external} aria-label="تواصل مع المدرسة عبر واتساب">${icon('wa')}</a><button class="back-to-top" type="button" aria-label="العودة إلى أعلى الصفحة" title="العودة إلى أعلى الصفحة" hidden><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 19V5m-7 7 7-7 7 7"/></svg></button><nav class="mobile-actions" aria-label="إجراءات سريعة"><a href="tel:+967773583041">${icon('phone')}اتصال</a><a href="${wa()}" ${external}>${icon('wa')}واتساب</a><a href="${url('admissions.html')}">${icon('book')}تسجيل</a><a href="${S.mapUrl}" ${external}>${icon('pin')}الموقع</a></nav>`;
}
const heading=(e,t,d='',a='')=>`<div class="section-head"><div><div class="eyebrow">${e}</div><h2>${t}</h2>${d?`<p>${d}</p>`:''}</div>${a}</div>`;
const intro=(t,d)=>`<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="${url('index.html')}">الرئيسية</a><span>/</span><span>${esc(page==='article'?'الأخبار':labels[page]||t)}</span></div><h1>${t}</h1><p>${d}</p></div></section>`;
const cta=()=>`<section class="section"><div class="container"><div class="cta"><div><div class="eyebrow" style="color:#d8eedf">لنبدأ رحلة المستقبل</div><h2>كل حلم كبير يبدأ بخطوة.</h2><p>تعرّف على مدرستنا، ودعنا نرافق ابنك في خطواته القادمة.</p></div><div class="actions">${link('admissions.html','قدّم طلب التسجيل','btn light')}${link('contact.html#visit','احجز زيارة','btn secondary')}</div></div></div></section>`;
const stageCards=()=>`<div class="grid grid-3 stage-grid">${S.stages.map(s=>`<article class="card stage-card">${photo(s.image,s.name,'card-image')}<div class="card-pad"><span class="tag">${s.grades}</span><h3>${s.name}</h3><p>${s.description}</p>${link('stages.html#'+s.id,'اكتشف المرحلة')}</div></article>`).join('')}</div>`;
const programCards=(data=S.programs)=>`<div class="grid grid-4">${data.map(([i,t,d])=>`<article class="card program-card"><div class="icon-box">${icon(i)}</div><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>`;
const faq=()=>`<div class="faq">${S.faqs.map(([q,a],i)=>`<details class="faq-item"><summary><span class="faq-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><span class="faq-question">${q}</span><span class="faq-toggle" aria-hidden="true"></span></summary><div class="faq-answer"><p>${a}</p></div></details>`).join('')}</div>`;
const newsCards=()=>`<div class="grid grid-3">${S.news.map(n=>`<article class="card news-card">${photo(n.image,n.title,'card-image')}<div class="card-pad"><div class="meta"><span class="tag">${n.category}${n.demo?' · نموذجي':''}</span><time datetime="${n.date}">${new Date(n.date).toLocaleDateString('ar-YE',{day:'numeric',month:'long',year:'numeric'})}</time></div><h3><a href="${url('news-detail.html?slug='+encodeURIComponent(n.slug))}">${n.title}</a></h3><p>${n.excerpt}</p>${link('news-detail.html?slug='+encodeURIComponent(n.slug),'اقرأ المقال')}</div></article>`).join('')}</div>`;
function home(){return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="pill">مدارس منار العلم النموذجية · عمران</div><h1>جيلٌ صاعد..<br><span>لغدٍ واعد.</span></h1><p>هنا تبدأ الحكاية. تعليم ينمّي المعرفة، وقيم تبني الشخصية، ومساحة يكتشف فيها كل طالب قدراته.</p><div class="actions">${link('admissions.html','ابدأ رحلة ابنك معنا','btn')}${link('about.html','تعرّف على المدرسة','btn secondary')}</div><div class="hero-foot">${icon('shield')}من الصف الأول إلى التاسع <span>•</span> نتعلّم، نكتشف، ونكبر معًا</div></div><div class="hero-visual"><div class="visual-frame"></div>${photo('pics/building.jpg','مبنى مدارس منار العلم النموذجية في عمران','hero-photo',true)}<span class="photo-label">${icon('pin')}مدرستنا في عمران</span><span class="sparkle" aria-hidden="true">✦</span><div class="hero-note"><span class="icon-box green">${icon('book')}</span><div><strong>من هنا، يُشرق المستقبل</strong><small>معرفة راسخة وقيم ترافقهم مدى الحياة</small></div></div></div></div></section><section class="stats" aria-label="إنجازاتنا بالأرقام"><div class="container stats-grid">${[['award',8,'سنوات الخبرة',''],['users',300,'عدد الطلاب','+'],['cap',30,'الكادر التعليمي','+'],['heart',99,'مؤشر الرضا','%']].map(([i,n,l,s])=>`<div class="stat" tabindex="0"><div class="icon-box">${icon(i)}</div><strong aria-label="${n}${s}"><bdi><span data-count="${n}">0</span>${s}</bdi></strong><span>${l}</span></div>`).join('')}</div></section>
<section class="section"><div class="container split"><div><div class="eyebrow">أهلًا بكم في منار العلم</div><h2>تعليم يتجاوز حدود<br>الفصل الدراسي.</h2><p>نؤمن أن لكل طفل موهبة تستحق أن تُكتشف، وحلمًا يستحق أن يكبر. في منار العلم، تبدأ رحلتنا مع الطالب بالمعرفة وتمتد إلى بناء شخصية واعية، واثقة، ومحبّة للتعلّم.</p><ul class="check-list"><li>المعرفة والقيم في قلب التجربة التعليمية</li><li>مساحة للمشاركة واكتشاف القدرات</li><li>الأسرة شريك أساسي في رحلة الأبناء</li></ul>${link('about.html','اكتشف قصتنا')}</div><div class="story-photo">${photo('pics/class.jpg','طلاب منار العلم في صفهم الدراسي','split-photo')}<div class="image-caption">كل سؤال بداية، وكل طالب حكاية تستحق الاهتمام.</div></div></div></section>
<section class="section tinted"><div class="container">${heading('خطوات تنمو معهم','لكل مرحلة، بداية تستحق الاهتمام.','من الحروف الأولى إلى آفاق أوسع؛ رحلة تراعي نمو الطالب واحتياجاته.',link('stages.html','المراحل التعليمية'))}${stageCards()}</div></section>
<section class="section"><div class="container">${heading('لماذا منار العلم؟','نبني المعرفة. ونرعى الإنسان.','تجربة تعليمية تتكامل فيها الدراسة والتربية والاهتمام.')}<div class="grid grid-4 feature-grid">${[['users','التعليم باهتمام','توجيه تربوي يقدّر الفروق الفردية ويشجّع المشاركة.'],['shield','بيئة تحترم الطالب','قيم الاحترام والانتماء أساس التعامل داخل المدرسة.'],['target','نمو نتابعه معًا','حوار متواصل بين الأسرة والمدرسة لدعم التقدّم.'],['spark','أكثر من منهج','فرص لاكتشاف المهارات وتوسيع آفاق التعلّم.']].map(([i,t,d])=>`<article class="card feature-card"><div class="icon-box ${i==='shield'?'green':''}">${icon(i)}</div><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></div></section>
<section class="section purple-section"><div class="container split"><div><div class="eyebrow">لأن التعلّم تجربة</div><h2>مواهب تُكتشف.<br>وذكريات تبقى.</h2><p>نقرأ، نبدع، ونتشارك الإنجاز. للأنشطة دور في بناء الثقة وتحويل المعرفة إلى تجربة قريبة من حياة الطالب.</p><div class="actions">${link('activities.html','اكتشف الحياة المدرسية','btn light')}${link('gallery.html','تصفّح المعرض','btn secondary')}</div></div><div class="story-photo">${photo('pics/475893074_645999404430664_4765200747018650688_n.jpg','تكريم طلاب المدرسة','split-photo')}<div class="image-caption">للتشجيع أثر يتجاوز اللحظة.</div></div></div></section>
<section class="section"><div class="container">${heading('مجالات تفتح الآفاق','معرفة متوازنة، ومهارات للحياة.','لغة وعلوم وتقنية، إلى جانب القيم والإبداع.',link('programs.html','جميع البرامج'))}${programCards(S.programs.slice(0,4))}</div></section>
<section class="section tinted"><div class="container">${heading('من مجتمع المدرسة','مساحة للمعرفة والإلهام.','مقالات تعريفية نموذجية؛ تُحدَّث بالأخبار المعتمدة من إدارة المدرسة.',link('news.html','جميع الأخبار'))}${newsCards()}</div></section>
<section class="section"><div class="container split"><div><div class="eyebrow">نلتقي قريبًا</div><h2>خطّط لزيارتك الأولى.</h2><p>زيارة المدرسة فرصة للتعرف إلى البيئة التعليمية ومناقشة احتياجات ابنك مع الإدارة.</p><div class="actions">${link('contact.html#visit','اطلب موعد زيارة','btn')}</div></div><div class="timeline"><div class="event"><div class="event-date">موعد<br>بالتنسيق</div><div><h3>زيارة تعريفية للمدرسة</h3><p>السبت – الأربعاء · الوقت يؤكَّد من الإدارة<br>مقر المدرسة، عمران</p></div></div><div class="event"><div class="icon-box">${icon('calendar')}</div><div><h3>الفعاليات القادمة</h3><p>لا توجد مواعيد فعاليات معلنة حاليًا. تابع هذه المساحة لمستجدات المدرسة.</p></div></div></div></div></section>
<section class="section tinted"><div class="container"><div class="section-center"><div class="eyebrow">الأسرة شريكتنا</div><h2>ثقة تنمو بالحوار.</h2><p>مساحة مخصصة لتجارب أولياء الأمور؛ تُنشر الشهادات بعد موافقة أصحابها واعتمادها من المدرسة.</p></div><div class="empty"><div class="icon-box green" style="margin:0 auto 15px">${icon('heart')}</div><h3>تجربتكم تستحق أن تُسمع</h3><p>هل أنت من أولياء أمور طلابنا؟ شارك المدرسة تجربتك.</p><a class="text-link" style="margin-top:15px" href="${wa('السلام عليكم، أود مشاركة تجربتي مع مدارس منار العلم.')}" ${external}>شارك تجربتك ${icon('arrow')}</a></div></div></section>
<section class="section faq-section faq-section-home"><div class="container"><div class="section-center"><div class="eyebrow">إجابات واضحة لأولياء الأمور</div><h2>قد تتساءل عن…</h2><p>جمعنا إجابات الأسئلة التي تساعدكم على بدء رحلة أبنائكم معنا بثقة.</p></div>${faq()}</div></section>${cta()}`;}
function about(){return intro('معرفة تنير العقول. وقيم تبني الإنسان.','تعرّف إلى مدارس منار العلم النموذجية، ورؤيتنا لتجربة تعليمية تنمو مع أبنائنا.')+`<section class="section"><div class="container split"><div><div class="eyebrow">قصتنا تبدأ بالطالب</div><h2>تعليم يتجاوز حدود الفصل الدراسي</h2><p>مدارس منار العلم النموذجية في عمران، للطلاب من الصف الأول إلى الصف التاسع. نحمل في اسمنا رسالة: أن تكون المعرفة نورًا يهدي الطالب إلى فهم نفسه والعالم من حوله.</p><p>نطمح إلى تجربة تجمع التحصيل الدراسي بالقيم والمهارات، وتمنح كل طالب فرصة المشاركة والتعلّم والمحاولة من جديد.</p><ul class="check-list"><li>الطالب في قلب الرحلة التعليمية</li><li>القيم ممارسة يومية</li><li>الشراكة مع الأسرة طريق للنمو</li></ul></div>${photo('pics/building.jpg','واجهة مبنى المدرسة','split-photo')}</div></section><section class="section tinted"><div class="container grid grid-3">${[['eye','رؤيتنا','جيل يمتلك المعرفة، ويعتز بقيمه، ويشارك بإيجابية في بناء مستقبله ومجتمعه.'],['target','رسالتنا','تقديم تجربة تعليمية تربط الفهم بالممارسة، وتنمّي مهارات الطالب في بيئة تحترم قدراته وطموحه.'],['heart','قيمنا','الاحترام، والأمانة، والمسؤولية، والتعاون، والإتقان؛ مبادئ نطمح إلى ترجمتها إلى سلوك كل يوم.']].map(([i,t,d])=>`<article class="card card-pad"><div class="icon-box">${icon(i)}</div><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section><section class="section" id="team"><div class="container">${heading('وراء كل خطوة، من يساندها','الهيئة التعليمية','فريق المدرسة هو شريك الطالب في الفهم والاكتشاف والنمو. تُضاف الأسماء والتخصصات بعد اعتمادها من الإدارة.')}<div class="grid grid-3">${[['users','الإدارة المدرسية','تنسيق العمل التربوي والتواصل مع الأسرة.'],['book','معلمو ومعلمات الصفوف','بناء المعرفة ودعم المهارات الأساسية.'],['heart','الإرشاد والمتابعة','مساندة الطالب وتعزيز علاقته بالتعلّم.']].map(([i,t,d])=>`<article class="card card-pad"><div class="teacher-placeholder">${icon(i)}</div><h3>${t}</h3><p>${d}</p><span class="tag">بيانات الفريق قريبًا</span></article>`).join('')}</div></div></section>${cta()}`;}
function stages(){return intro('خطوة بخطوة، ينمو المستقبل.','من الصف الأول إلى التاسع؛ ثلاث محطات متصلة لبناء المعرفة والمهارات والثقة.')+`<section class="section"><div class="container">${S.stages.map(s=>`<article class="detail-block" id="${s.id}"><div class="split"><div><span class="tag">${s.grades}</span><h2 style="margin-top:15px">${s.name}</h2><h3 style="margin-top:16px">${s.title}</h3><p>${s.description}</p><ul class="check-list">${s.points.map(p=>`<li>${p}</li>`).join('')}</ul>${link('admissions.html?stage='+s.id,'طلب التسجيل في هذه المرحلة','btn')}</div>${photo(s.image,s.name,'split-photo')}</div></article>`).join('')}</div></section>${cta()}`;}
function programs(){return intro('نتعلّم لنفهم. ونفهم لنبتكر.','مجالات معرفية ومهارية متكاملة ترافق رحلة الطالب من الصف الأول إلى التاسع.')+`<section class="section"><div class="container">${programCards()}</div></section><section class="section tinted"><div class="container split"><div><div class="eyebrow">من المعرفة إلى الممارسة</div><h2>التعلّم لا يتوقف عند الإجابة.</h2><p>نريد للطالب أن يعرف كيف يسأل، ويبحث، ويشرح ما فهمه. الأنشطة الصفية والقراءة والتطبيق تساعده على تحويل المعلومات إلى مهارات يستخدمها بثقة.</p><ul class="check-list"><li>مهارات تتدرج مع العمر والصف الدراسي</li><li>مساحة للسؤال والمشاركة والتعاون</li><li>ربط التعلّم بالحياة اليومية</li></ul></div>${photo('pics/class.jpg','التعلّم داخل الصف','split-photo')}</div></section>${cta()}`;}
function activities(){return intro('هنا تتّسع مساحة الاكتشاف.','الأنشطة مساحة للطالب ليجرّب ويتعاون ويكتشف ما يحب. تُحدَّد المواعيد بحسب خطة المدرسة.')+`<section class="section"><div class="container"><div class="activity-cover">${photo('pics/gifts.jpg','هدايا تقديرية من المدرسة')}${photo('pics/class.jpg','طلاب داخل الفصل')}</div>${programCards(S.activities)}</div></section><section class="section tinted"><div class="container">${heading('تقويم المدرسة','الفعاليات القادمة','تُعلن التفاصيل والمواعيد بعد اعتمادها من الإدارة.')}<div class="event"><div class="icon-box">${icon('calendar')}</div><div><h3>نستعد للقاءات جديدة</h3><p>لا توجد فعاليات مجدولة معلنة حاليًا. يمكنك طلب زيارة تعريفية في مقر المدرسة، من السبت إلى الأربعاء، بموعد تؤكده الإدارة.</p>${link('contact.html#visit','احجز زيارة')}</div></div></div></section>${cta()}`;}
function gallery(){return intro('لحظات من عالم منار العلم.','صور من مبنى المدرسة وصفوفها ولمسات التقدير فيها. اختر الصور أو الفيديوهات لاستكشاف لحظات من الحياة المدرسية.')+`<section class="section gallery-section"><div class="container"><div class="section-head"><div><div class="eyebrow">حكايات وذكريات</div><h2>معرض الصور والفيديوهات</h2><p>من تفاصيل الصف إلى لحظات الإنجاز، نافذة على يوميات مجتمعنا المدرسي.</p></div></div><div class="media-tabs" id="gallery-tabs" role="tablist" aria-label="نوع الوسائط"><button class="media-tab active" id="photos-tab" role="tab" aria-selected="true" aria-controls="photos-panel" tabindex="0"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg><span>الصور</span><small>${S.gallery.length}</small></button><button class="media-tab" id="videos-tab" role="tab" aria-selected="false" aria-controls="videos-panel" tabindex="-1"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="4"/><path d="m10 9 5 3-5 3z"/></svg><span>الفيديوهات</span><small>${(S.videos||[]).length}</small></button></div><section id="photos-panel" class="media-panel" role="tabpanel" aria-labelledby="photos-tab"><div class="gallery-filters" role="group" aria-label="تصفية صور المدرسة">${['الكل',...new Set(S.gallery.map(g=>g.category))].map((c,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${esc(c)}" aria-pressed="${i===0}">${esc(c)}</button>`).join('')}</div><div id="gallery-grid" class="grid grid-2"></div><p class="screen-reader" id="gallery-status" role="status"></p></section><section id="videos-panel" class="media-panel" role="tabpanel" aria-labelledby="videos-tab" hidden><div id="video-grid" class="grid grid-3"></div><p class="screen-reader" id="video-status" role="status"></p></section></div></section><dialog class="lightbox" aria-label="عارض الصور"><div class="dialog-bar"><span id="lightbox-title"></span><button class="close-dialog" aria-label="إغلاق الصورة">×</button></div><img id="lightbox-image" alt=""><div class="dialog-bar"><button class="btn secondary small" id="previous-image">الصورة السابقة</button><span id="image-counter"></span><button class="btn secondary small" id="next-image">الصورة التالية</button></div></dialog>${cta()}`;}
function news(){return intro('من مجتمع المدرسة.','معرفة تربوية، وقصص تعلّم، ومساحة لمستجدات منار العلم.')+`<section class="section"><div class="container"><div class="notice">المقالات المعلّمة بأنها نموذجية للتعريف والمراجعة؛ أما مستجدات المدرسة فتُنشر بعد اعتماد الإدارة.</div>${newsCards()}</div></section>${cta()}`;}
function article(){const slug=document.body.dataset.slug||new URLSearchParams(location.search).get('slug');const n=S.news.find(n=>n.slug===slug);if(!n)return notFound();return intro(n.title,n.excerpt)+`<section class="section"><article class="container article"><div class="meta"><span class="tag">${n.category}</span><time datetime="${n.date}">${new Date(n.date).toLocaleDateString('ar-YE',{day:'numeric',month:'long',year:'numeric'})}</time>${n.demo?'<span>مقال نموذجي</span>':''}</div>${photo(n.image,n.title,'article-cover',true)}<h2>${n.title}</h2>${n.content.map(t=>`<p>${t}</p>`).join('')}<div class="article-actions">${link('news.html','العودة إلى الأخبار','btn secondary')}<button class="btn" id="share-article">${icon('share')}مشاركة المقال</button></div><p id="share-status" role="status"></p></article></section>`;}
const input=(name,label,type='text',required=true,extra='')=>`<div class="field"><label for="${name}">${label}${required?' <span class="required" aria-hidden="true">*</span>':''}</label><input id="${name}" name="${name}" type="${type}" ${required?'required':''} ${extra} maxlength="${type==='tel'?20:150}"></div>`;
const select=(name,label,options)=>`<div class="field"><label for="${name}">${label} <span class="required" aria-hidden="true">*</span></label><select id="${name}" name="${name}" required><option value="">اختر ${label}</option>${options.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></div>`;
const notes=(id,label='ملاحظات إضافية')=>`<div class="field full"><label for="${id}">${label} <span style="font-weight:400;color:var(--muted)">(اختياري)</span></label><textarea name="${id}" id="${id}" maxlength="1200" rows="3"></textarea></div>`;
const formEnd=()=>`<p class="form-note">الحقول المعلّمة بـ * مطلوبة. لا تُحفظ البيانات في الموقع. تُجهّز في رسالة واتساب لتراجعها وترسلها بنفسك إلى المدرسة.</p><button class="btn green" style="margin-top:22px" type="submit">${icon('wa')}تجهيز الطلب عبر واتساب</button><div class="form-result" role="status" aria-live="polite"></div>`;
const grades=['الأول','الثاني','الثالث','الرابع','الخامس','السادس','السابع','الثامن','التاسع'].map(g=>'الصف '+g);
function admissions(){return intro('خطوتكم الأولى نحو غدٍ واعد.','يسعدنا انضمامكم إلى مجتمع منار العلم. أرسلوا طلبًا أوليًا، وسنساعدكم في استكمال رحلة التسجيل.')+`<section class="section"><div class="container form-layout"><div><form class="form-card" data-kind="admission"><h2>طلب تسجيل طالب</h2><p>املأ البيانات التالية بدقة. إرسال الطلب لا يعني تأكيد القبول أو حجز المقعد.</p><div class="form-grid">${input('student','اسم الطالب الرباعي','text',true,'autocomplete="name" minlength="6"')}${input('birth','تاريخ الميلاد','date')}${select('gender','الجنس',['ذكر','أنثى'])}${select('grade','الصف المطلوب',grades)}${input('guardian','اسم ولي الأمر','text',true,'minlength="4"')}${input('phone','رقم الهاتف','tel',true,'autocomplete="tel" inputmode="tel"')}${input('whatsapp','رقم واتساب','tel',true,'inputmode="tel"')}${input('email','البريد الإلكتروني (اختياري)','email',false,'autocomplete="email"')}<div class="field full"><label for="address">العنوان <span class="required">*</span></label><input id="address" name="address" autocomplete="street-address" required minlength="5" maxlength="250"></div>${notes('notes')}</div>${formEnd()}</form></div><aside><div class="aside-card"><h3>التسجيل في ٤ خطوات</h3><ol class="steps"><li><strong>أرسل طلبك</strong><span>جهّز البيانات وتواصل عبر واتساب.</span></li><li><strong>تواصل مع الإدارة</strong><span>تعرّف على المقاعد والرسوم والشروط.</span></li><li><strong>استكمل المستندات</strong><span>تؤكد الإدارة متطلبات الصف المطلوب.</span></li><li><strong>تأكيد القبول</strong><span>بعد المراجعة واستكمال الإجراءات.</span></li></ol></div><div class="aside-card"><h3>ماذا أُجهّز مبدئيًا؟</h3><ul class="check-list"><li>شهادة ميلاد الطالب</li><li>صور شخصية حديثة</li><li>نتائج العام السابق للطلاب المنقولين</li><li>بيانات ولي الأمر ووسائل التواصل</li></ul><p>قائمة استرشادية؛ تؤكد الإدارة المتطلبات النهائية وشروط العمر والقبول. يرجى عدم إرسال صور المستندات في الطلب الأولي.</p></div><div class="aside-card"><h3>المراحل المتاحة</h3><p>من الصف الأول إلى الصف التاسع، وفق المقاعد المتاحة والشروط التي تعتمدها الإدارة.</p><a class="text-link" href="${wa('السلام عليكم، أود معرفة شروط التسجيل والرسوم الدراسية.')}" ${external}>استفسر عن القبول ${icon('arrow')}</a></div></aside></div></section><section class="section tinted faq-section faq-section-admissions"><div class="container"><div class="section-center"><div class="eyebrow">كل ما تحتاجون معرفته</div><h2>أسئلة التسجيل والقبول</h2><p>إجابات مختصرة تساعدكم على اتخاذ الخطوة التالية بوضوح.</p></div>${faq()}</div></section>`;}
function contact(){return intro('نرحّب بأسئلتكم. ونسعد بلقائكم.','اختر الطريقة الأنسب للتواصل معنا، أو اطلب زيارة للتعرف إلى المدرسة عن قرب.')+`<section class="section"><div class="container split"><div>${[['pin','زورونا في عمران',esc(S.address)],['phone','اتصل بنا','<a href="tel:+967773583041"><bdi>+967 773 583 041</bdi></a>'],['clock','أيام الدوام',S.hours+' · تواصل معنا لتأكيد ساعات الحضور اليومية.'],['facebook','صفحة المدرسة على فيسبوك',`<a href="${S.facebook}" ${external}>مدارس منار العلم النموذجية</a>`],['mail','البريد الإلكتروني','لا يتوفر بريد إلكتروني معلن حاليًا. يسعدنا استقبال رسالتك عبر واتساب.']].map(([i,t,d])=>`<div class="contact-item"><span class="icon-box">${icon(i)}</span><div><strong>${t}</strong><p>${d}</p></div></div>`).join('')}<div class="actions" style="margin-top:16px"><a class="btn green" href="${wa()}" ${external}>${icon('wa')}تواصل عبر واتساب</a><a class="btn secondary" href="${S.facebook}" ${external}>${icon('facebook')}صفحتنا على فيسبوك</a></div></div><div class="map-box" id="map"><div><span class="icon-box green" style="margin:0 auto 15px">${icon('pin')}</span><h3>مدارس منار العلم النموذجية</h3><p>${esc(S.address)}</p><a class="btn secondary" href="${S.mapUrl}" ${external}>افتح العنوان في خرائط Google ${icon('arrow')}</a><p style="font-size:12px">موقع المدرسة المعتمد على خرائط Google.</p></div></div></div></section><section class="section tinted"><div class="container grid grid-2"><form class="form-card" data-kind="message"><h2>لديك سؤال؟ نحن هنا.</h2><p>أخبرنا بما تحتاجه وسنساعدك في الوصول إلى المعلومة.</p><div class="form-grid">${input('sender','الاسم','text',true,'autocomplete="name" minlength="3"')}${input('message-phone','رقم الهاتف','tel',true,'autocomplete="tel" inputmode="tel"')}${input('message-email','البريد الإلكتروني (اختياري)','email',false)}${select('subject','موضوع الرسالة',['التسجيل والقبول','الرسوم الدراسية','متابعة طالب','استفسار عام'])}<div class="field full"><label for="message">رسالتك <span class="required">*</span></label><textarea id="message" name="message" required minlength="10" maxlength="1500" rows="5"></textarea></div></div>${formEnd()}</form><form class="form-card" data-kind="visit" id="visit"><h2>احجز زيارة للمدرسة</h2><p>اختر يومًا ووقتًا مناسبين. يصبح الموعد مؤكدًا بعد رد الإدارة على طلبك.</p><div class="form-grid">${input('visitor','الاسم','text',true,'autocomplete="name" minlength="3"')}${input('visit-phone','رقم الهاتف','tel',true,'autocomplete="tel" inputmode="tel"')}${input('visit-date','اليوم المقترح','date')}${input('visit-time','الوقت المقترح','time')}${input('visitors','عدد الزوار','number',true,'min="1" max="10" step="1" value="1"')}${notes('visit-notes')}</div>${formEnd()}</form></div></section>${cta()}`;}
function notFound(){return `<section class="error-page container"><strong>404</strong><h1>يبدو أننا سلكنا ممرًا آخر.</h1><p>الصفحة المطلوبة غير موجودة. لنعد إلى بداية الرحلة.</p><div class="actions">${link('index.html','العودة للرئيسية','btn')}${link('contact.html','تواصل معنا','btn secondary')}</div></section>`;}
S.news = [...(window.EDITOR_CONTENT?.news||[]),...S.news];
chrome();
$('#main').innerHTML=({home,about,stages,programs,activities,gallery,news,article,admissions,contact,'404':notFound}[page]||notFound)();
const menu=$('.menu-toggle'),nav=$('#navigation');
const closeMenu=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','فتح القائمة');};
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'إغلاق القائمة':'فتح القائمة');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});
matchMedia('(min-width:1151px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
$$('.faq details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)$$('.faq details').filter(x=>x!==d).forEach(x=>x.open=false);}));
if(page==='gallery'){
 let filtered=[...S.gallery],index=0,trigger=null;
 const grid=$('#gallery-grid'),dialog=$('.lightbox'),photosPanel=$('#photos-panel'),videosPanel=$('#videos-panel'),videoGrid=$('#video-grid');
 const show=()=>{const item=filtered[index];$('#lightbox-image').src=url(item.src);$('#lightbox-image').alt=item.alt;$('#lightbox-title').textContent=item.title;$('#image-counter').textContent=(index+1)+' / '+filtered.length;$('#previous-image').disabled=$('#next-image').disabled=filtered.length<2;};
 const render=()=>{grid.innerHTML=filtered.length?filtered.map((g,i)=>`<button class="gallery-item" data-image="${i}" aria-label="عرض ${esc(g.title)}">${photo(g.src,g.alt)}<span>${esc(g.title)}<small>${esc(g.category)}</small></span></button>`).join(''):'<div class="empty"><h3>صور جديدة قريبًا</h3><p>لم تُضف صور لهذا التصنيف بعد. يمكنك استكشاف بقية لحظات المدرسة.</p></div>';$('#gallery-status').textContent=filtered.length+' صور';};render();
 const videos=S.videos||[];videoGrid.innerHTML=videos.length?videos.map(v=>`<article class="video-card"><div class="video-frame"><video controls playsinline preload="none"${v.poster?` poster="${esc(url(v.poster))}"`:''}><source src="${esc(url(v.src))}" type="${esc(v.type||'video/mp4')}">المتصفح لا يدعم تشغيل هذا الفيديو.</video></div><div class="video-card-copy"><span class="tag">${esc(v.category||'من حياة المدرسة')}</span><h3>${esc(v.title)}</h3>${v.description?`<p>${esc(v.description)}</p>`:''}</div></article>`).join(''):`<div class="video-empty"><div class="video-empty-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="4"/><path d="m10 9 5 3-5 3z"/></svg></div><span class="eyebrow">قريبًا في معرضنا</span><h3>لحظات المدرسة بالفيديو</h3><p>نعمل على تجهيز المقاطع المرئية من الأنشطة والحياة المدرسية. حتى ذلك الحين، يمكنكم زيارة صفحة المدرسة لمشاهدة ما تشاركه.</p><a class="btn" href="${esc(S.facebook)}" target="_blank" rel="noopener noreferrer">تابعوا مقاطع المدرسة ${icon('arrow')}</a></div>`;$('#video-status').textContent=videos.length?videos.length+' فيديوهات':'الفيديوهات قيد الإضافة';
 const tabs=[$('#photos-tab'),$('#videos-tab')];const activateTab=(tab,focus=false)=>{const showVideos=tab===$('#videos-tab');tabs.forEach(t=>{const active=t===tab;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});photosPanel.hidden=showVideos;videosPanel.hidden=!showVideos;if(!showVideos)$$('video',videosPanel).forEach(v=>v.pause());if(focus)tab.focus();};tabs.forEach(tab=>tab.addEventListener('click',()=>activateTab(tab)));$('#gallery-tabs')?.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.indexOf(document.activeElement);const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;activateTab(tabs[next],true);});
 $$('.filter',photosPanel).forEach(b=>b.addEventListener('click',()=>{$$('.filter',photosPanel).forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});filtered=S.gallery.filter(g=>b.dataset.filter==='الكل'||g.category===b.dataset.filter);render();}));
 grid.addEventListener('click',e=>{const b=e.target.closest('[data-image]');if(!b)return;trigger=b;index=Number(b.dataset.image);show();dialog.showModal();document.body.style.overflow='hidden';});
 $('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow='';trigger?.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 const move=d=>{index=(index+d+filtered.length)%filtered.length;show();};$('#previous-image').addEventListener('click',()=>move(-1));$('#next-image').addEventListener('click',()=>move(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')move(-1);if(e.key==='ArrowLeft')move(1);});
}
const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());const todayString=today.toISOString().slice(0,10);
if($('#birth')){$('#birth').max=todayString;$('#birth').min='1990-01-01';}
if($('#visit-date'))$('#visit-date').min=todayString;
if(page==='admissions'){const stage=new URLSearchParams(location.search).get('stage');const n={foundation:0,growth:3,future:6}[stage];if(n!==undefined)$('#grade').value=grades[n];}
const normalizeDigits=s=>s.replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776));
const fieldNames={student:'اسم الطالب',birth:'تاريخ الميلاد',gender:'الجنس',grade:'الصف المطلوب',guardian:'ولي الأمر',phone:'الهاتف',whatsapp:'واتساب',email:'البريد',address:'العنوان',notes:'ملاحظات',sender:'الاسم','message-phone':'الهاتف','message-email':'البريد',subject:'الموضوع',message:'الرسالة',visitor:'اسم الزائر','visit-phone':'الهاتف','visit-date':'يوم الزيارة','visit-time':'وقت الزيارة',visitors:'عدد الزوار','visit-notes':'ملاحظات'};
$$('form[data-kind]').forEach(form=>{
 const result=$('.form-result',form);
 const validate=()=>{$$('input,textarea',form).forEach(el=>{el.setCustomValidity('');if(el.required&&el.value&&!el.value.trim())el.setCustomValidity('يرجى إدخال قيمة صحيحة.');if(el.type==='tel'&&el.value){const digits=normalizeDigits(el.value).replace(/[\s()-]/g,'');if(!/^\+?\d{9,15}$/.test(digits))el.setCustomValidity('أدخل رقم هاتف صحيحًا من 9 إلى 15 رقمًا.');}if(el.id==='visit-date'&&el.value){const day=new Date(el.value+'T12:00:00').getDay();if(day===4||day===5)el.setCustomValidity('اختر يومًا من السبت إلى الأربعاء.');}});};
 form.addEventListener('input',()=>{result.innerHTML='';validate();});
 form.addEventListener('submit',e=>{e.preventDefault();validate();if(!form.reportValidity())return;
 const title={admission:'طلب تسجيل طالب',visit:'طلب زيارة للمدرسة',message:'رسالة إلى المدرسة'}[form.dataset.kind];
 const lines=[title,'مدارس منار العلم النموذجية',''];for(const [key,value] of new FormData(form)){if(String(value).trim())lines.push((fieldNames[key]||key)+': '+String(value).trim());}
 result.innerHTML=`<strong>تم تجهيز ${title} بنجاح.</strong><p>لم يُرسَل بعد. اضغط الزر التالي، وراجع الرسالة داخل واتساب ثم أرسلها. ${form.dataset.kind==='visit'?'الموعد بانتظار تأكيد الإدارة.':''}</p><a class="btn green" href="${esc(wa(lines.join('\n')))}" ${external}>${icon('wa')}فتح واتساب وإرسال الطلب</a>`;
 result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'nearest'});
 });
});
if($('#share-article'))$('#share-article').addEventListener('click',async()=>{const status=$('#share-status');if(location.protocol==='file:'){status.textContent='مشاركة رابط المقال متاحة بعد نشر الموقع على الإنترنت.';return;}try{if(navigator.share){await navigator.share({title:document.title,url:location.href});status.textContent='تم فتح المشاركة.';}else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);status.textContent='تم نسخ رابط المقال.';}else{status.textContent='رابط المقال: '+location.href;}}catch(e){if(e.name!=='AbortError')status.textContent='تعذرت المشاركة تلقائيًا. يمكنك نسخ الرابط من شريط العنوان.';}});
if(location.hash)requestAnimationFrame(()=>{const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));target?.scrollIntoView();});
})();


