import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import vm from 'node:vm';
const context={window:{}};vm.runInNewContext(await readFile('js/data.js','utf8'),context);const school=context.window.SCHOOL;
const pages=[['index.html','home','مدارس منار العلم النموذجية | جيل صاعد.. لغد واعد','مدارس منار العلم النموذجية في عمران. تعليم من الصف الأول إلى التاسع، برامج وأنشطة، وتسجيل عبر واتساب.'],['about.html','about','عن المدرسة','تعرّف على رؤية ورسالة وقيم مدارس منار العلم النموذجية في عمران.'],['stages.html','stages','المراحل التعليمية','رحلة تعليمية متكاملة من الصف الأول إلى التاسع في مدارس منار العلم.'],['programs.html','programs','البرامج الأكاديمية','اكتشف مجالات اللغة والرياضيات والعلوم والقرآن والتقنية والمهارات الحياتية.'],['activities.html','activities','الحياة المدرسية والأنشطة','أنشطة رياضية وثقافية وعلمية وفنية تفتح آفاق الطالب.'],['gallery.html','gallery','معرض الصور والفيديوهات','تصفّح صور المدرسة ومقاطع الفيديو من الصفوف والأنشطة ولحظات التقدير.'],['news.html','news','الأخبار والمقالات','مقالات تربوية وتعريفية ومساحة لأخبار مجتمع المدرسة.'],['admissions.html','admissions','التسجيل والقبول','قدّم طلب تسجيل أولي من الصف الأول إلى التاسع عبر واتساب.'],['contact.html','contact','تواصل معنا واحجز زيارة','عمران - شارع 22 مايو - ذعوان - أمام حوش الزبيدي. واتساب 773583041. الدوام السبت إلى الأربعاء.'],['404.html','404','الصفحة غير موجودة','العودة إلى موقع مدارس منار العلم النموذجية.'],['news-detail.html','article','تفاصيل المقال','مقالات مجتمع مدارس منار العلم.']];
for(const n of school.news)pages.push(['news/'+n.slug+'/index.html','article',n.title,n.excerpt,n.slug]);
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for(const [path,id,title,desc,slug]of pages){const base=path.includes('/')?'../../':'./';const fullTitle=id==='home'?title:title+' | منار العلم النموذجية';const html=`<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#51479a"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(desc)}"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="${id==='article'?'article':'website'}"><meta property="og:locale" content="ar_YE"><meta property="og:site_name" content="مدارس منار العلم النموذجية">${id==='404'?'<meta name="robots" content="noindex">':''}<link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}css/fonts.css"><link rel="stylesheet" href="${base}css/styles.css"><link rel="stylesheet" href="${base}css/upgrade.css"><script src="${base}js/data.js" defer></script><script src="${base}js/content.js" defer></script><script src="${base}js/app.js" defer></script><script src="${base}js/enhancements.js" defer></script></head>
<body data-page="${id}" data-base="${base}"${slug?' data-slug="'+slug+'"':''}><div id="site-header"></div><main id="main" tabindex="-1"></main><div id="site-footer"></div><noscript><h1>مدارس منار العلم النموذجية</h1><p>يرجى تفعيل JavaScript لاستخدام القوائم والنماذج. للتواصل: <a href="tel:+967773583041">+967 773583041</a> | <a href="https://www.facebook.com/manar00000000/">صفحة فيسبوك</a></p><p>عمران - شارع 22 مايو - ذعوان - أمام حوش الزبيدي</p></noscript></body></html>`;
if(path.includes('/'))await mkdir(path.substring(0,path.lastIndexOf('/')),{recursive:true});await writeFile(path,html);}
await mkdir('dist',{recursive:true});for(const name of ['assets','css','js','pics','video','news'])await cp(name,'dist/'+name,{recursive:true});for(const [path]of pages)if(!path.includes('/'))await cp(path,'dist/'+path);
const rewrites=['about','stages','programs','activities','news','gallery','admissions','contact'].map(p=>({source:'/'+p,destination:'/'+p+'.html'}));
await writeFile('vercel.json',JSON.stringify({version:2,buildCommand:'npm run build',outputDirectory:'dist',cleanUrls:false,rewrites,headers:[{source:'/(.*)',headers:[{key:'X-Content-Type-Options',value:'nosniff'},{key:'Referrer-Policy',value:'strict-origin-when-cross-origin'},{key:'X-Frame-Options',value:'SAMEORIGIN'}]}]},null,2));
console.log('Built '+pages.length+' static HTML pages. Open index.html directly or run npm start.');

await cp('content.json','dist/content.json');

